# Generated by Django 3.2.9 on 2021-11-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormModel',
            new_name='ContactForm',
        ),
        migrations.RenameModel(
            old_name='PortfolioModel',
            new_name='Portfolio',
        ),
    ]
